### ISSUE TITLE
Bug: Major: TOPICS section is not displayed in search results

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#109]
**Steps:**
1.  Navigate to https://43-search-results--vg-roadchoice-com--hlxsites.hlx.page/
2.  Click on Part Number,  select Make as 'Autocar' and click on search.  
   **OR**  
      Click on Cross reference number, enter AD642098 and click on search 
3.  Validate the search results 

**Expected** 
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/7cf2cfda-f8d9-44cb-8fe2-ac30dc8dd01a">

**Actual:**
TOPICS section is not displayed; Only CATEGORIES section is displayed

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/8e6bbb3e-c01a-4638-914f-8e397ebdaf34)

**Comment by jonatan-lledo-netcentric** [comment]
@janedbarra this is needed? if yes, from where is taking the data to fill the topics filter block

**Comment by janedbarra** [comment]
@jonatan-lledo-netcentric no, I don't think the topic filter block is necessary. We can leave it off for now.

**Comment by ZoeBeykirch** [comment]
Closing this issue as we don't specifically need to bring the topics filter back, as the search will be improved with some of the work going on separately.
