### ISSUE TITLE
NFR: Integrate GTM (GA) and Hotjar on RoadChoice.com

### ISSUE THREAD

**Issue by verareljic** [hlxsites/vg-roadchoice-com#11]

**Comment by shirin27** [comment]
@ZoeBeykirch could you please add the scripts for this?

**Comment by Kannan-CM** [comment]
Here is the GTM ID:
Head Tag:


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MJJCNZK');</script>


For Body Tag:


<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MJJCNZK"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by girishdigrajkar** [comment]
Marking this ticket on hold since the code is not combined with cookie implementation.
Due to this limitation of the dev environment this needs to be verified post go live.
Also, new ticket for cookie integration of hotjar is needed to go ahead with implementation.

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd Please take a look at this one and determine if it can be planned for a future sprint or if it has been handled. Thank you!
