### ISSUE TITLE
Bug: Minor: PDP parts manual block has incorrect label 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#120]
**Steps:**
1. Navigate to https://77-pdp-template--vg-roadchoice-com--hlxsites.hlx.page/parts?category=batteries&sku=27FCRC
2. Expand the Parts Manual section
3. Validate the label 

**Expected as per user story AC:**
<img width="1205" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/7a0d1ad6-2c46-4f94-bb6a-9c6990f05f5d">

**Actual Result :**
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/47667294-d93b-4baf-a81b-90ad99f9df8a)

**Comment by jonatan-lledo-netcentric** [comment]
it's okay if the manual table list rest as it is now? @janedbarra @BeckyMedlin ?

**Comment by janedbarra** [comment]
@BeckyMedlin is this the one we previously discussed? That it would have the language in the left column and then the link to the manual PDFs in the right column? If so, that is fine with me.

**Comment by girishdigrajkar** [comment]
As per confirmation in #121 marking this bug to done.
