### ISSUE TITLE
Bug: Medium: Links are not configured in & Incorrect Label is noted in CATALOGS, PRODUCT SHEETS, ECATALOGS AND MORE

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#121]
**Steps:**
1. Navigate to https://77-pdp-template--vg-roadchoice-com--hlxsites.hlx.page/parts?category=batteries&sku=27FCRC
2. Expand the  CATALOGS, PRODUCT SHEETS, ECATALOGS AND MORE section
3. Validate the links of **Learn more in our brand brochure**.  &  **Search our All-Makes Parts and Accessories Catalog**
4. Validate the Label in the table
 
**Expected Result:**
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/e19991b5-6b31-4c52-b0a3-ca3fd39f8e00)

**Actual Result:**
1. Link is not set for  **Learn more in our brand brochure**.  &  **Search our All-Makes Parts and Accessories Catalog**
2.  Label is not set correctly in the table 
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/c29e51f8-6429-412c-89d0-8c3a5399b890)

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/857e9cb4-ace3-42d6-a57f-108e6db8046a">

**Comment by girishdigrajkar** [comment]
**Partially fixed**
Validated and able to see correct links configured however, labels in table column are not as expected hence, **reopening the defect.** 

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/78221470-d489-450c-b195-b7ccdadce82f)

**Comment by Gonzalo-CG** [comment]
@girishdigrajkar @jonatan-lledo-netcentric  Becky confirmed that they want to keep the labels as "ENGLISH, SPANISH, FRENCH" so no further modifications are needed on this ticket.
