### ISSUE TITLE
NFR: Create Robots.txt for RoadChoice.com

### ISSUE THREAD

**Issue by verareljic** [hlxsites/vg-roadchoice-com#13]

**Comment by girishdigrajkar** [comment]
Parking this ticket to 'On Hold' until we go live; 
Dev team needs to verify the source code for 'Robots.txt' availability before marking this ticket to closed.

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG Can we move this one to the backlog since it's on hold until go-live?
