### ISSUE TITLE
Bug: Minor: The label shown related to records is not as expected

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#133]
**Steps:**
1. Navigate to https://55-pdp-part-fit--vg-roadchoice-com--hlxsites.hlx.page/parts?category=charge-air-coolers&sku=CAC41165
2. Go to 'Will This Part Fit My Vehicle?' section and expand it 
3.  search for 'Autocar' and click on magnifying glass icon 
4. Validate the Label displayed above the cards

**Expected vs Actual:**
As per design "Showing 2 of 3 Entries" should be displayed instead shows ""

**Actual:**
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/7dd6def9-3efa-421f-b09c-72133709eefe)

 Figma **design:**
 https://www.figma.com/file/6bHOxjYFCkseuztuTch5pv/roadchoice?type=design&node-id=0-1&mode=design&t=yx8y9G55vXsslyfA-0
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/85c3f302-cb58-44c0-895e-e6983759c642">

**Comment by ZoeBeykirch** [comment]
Jane confirmed what is live on production is fine as is, so we can close this as not needed.
