### ISSUE TITLE
Bug: Medium: Product subcategory filter is not correctly displayed in case older browser version

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#139]
**Steps:**
1. Navigate to https://78-product-subcategory-template--vg-roadchoice-com--hlxsites.hlx.page/part-category/?category=batteries   **OR** https://main--vg-roadchoice-com--hlxsites.hlx.page/part-category/?category=batteries
2. Verify the filter

**Expected vs Actual:**
The filter is not displayed correctly 
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/aff94b45-373e-4bdf-9455-b01195be84b1">

**Expected:**
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/0fa49882-254b-4f24-8641-5e8ca2ddaf03">

Browser version used: Chrome Version 110.0.5481.177

**Comment by jonatan-lledo-netcentric** [comment]
more info about this issue in the "_can I use_" page
https://caniuse.com/css-nesting

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking the bug to done status:

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/b303722d-2a5d-4bfd-b3db-1b477a2a9a5b)
