### ISSUE TITLE
Testing: Site testing for RoadChoice.com

### ISSUE THREAD

**Issue by verareljic** [hlxsites/vg-roadchoice-com#14]
**Description**
- The scope of this ticket includes testing of the full sections/pages of the site

**Comment by shirin27** [comment]
Dependency with content being created by CMS team - move to sprint 13.

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG Can we get this one planned for a future sprint?

**Comment by BeckyMedlin** [comment]
@girishdigrajkar Are you working this ticket?

**Comment by girishdigrajkar** [comment]
Yes @BeckyMedlin;
Testing in progress :
Defects and observations are being recorded in #207 & #191

**Comment by girishdigrajkar** [comment]
Validation has been done for roadchoice; For outstanding issues small regression activity will be carried out post issues are closed.
