### ISSUE TITLE
FR: Add all RoadChoice blocks to Sidekick library 

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-roadchoice-com#143]
### Description
After adding the Sidekick library to the project is done (#34), we must add all the blocks to said library.

### Acceptance Criteria
- [x] All RoadChoice blocks are present on the Sidekick library.

**Comment by girishdigrajkar** [comment]
Validated and not able to see below blocks, @SantiagoHomps-NC :could you please confirm 

Pardot block #68
Blog List block         #2
Header & Nav Block  #6
Footer block #17
Search Results block #43

**Comment by SantiagoHomps-NC** [comment]
@girishdigrajkar 
Pardot block is called Iframe and inside it there are the 3 variations
Blog list is called blog-results
Header, footer and nav are not block to be used in pages
and search results is a template and not intended to be used as a block

**Comment by girishdigrajkar** [comment]
Thanks for clarification @SantiagoHomps-NC , Marking the ticket to done status as able to see the blocks as expected.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/08bcd6fc-673f-4040-a267-4ac4b7ee0c8c">

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/94dabece-4ca9-426f-a3fe-dca6a384afd3">
