### ISSUE TITLE
Task: Content editing

### ISSUE THREAD

**Issue by verareljic** [hlxsites/vg-roadchoice-com#15]

**Comment by BeckyMedlin** [comment]
@Kannan-CM Can this one be closed? It's in a closed sprint. Thanks!

**Comment by Gonzalo-CG** [comment]
@Kannan-CM it was discussed during today's planning that content should be ready by the first week of sprint 18 in order for everything to be ready for testing.

**Comment by janedbarra** [comment]
@manuel-vara yes, all of the subcategory data files are uploaded now.
