### ISSUE TITLE
CR: Special g glyph

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-roadchoice-com#152]
### Description
The Nexa-Regular font used on the site renders the lowercase "g" as seen in image 1, but as part of the RoadChoice brand image, that letter should be rendered as seen in image 2.

Image 1 (how it looks currently in Franklin):
<img src="https://github.com/hlxsites/vg-roadchoice-com/assets/139977780/5292cf17-709c-4b65-b21a-c730319a7eee" width="200px">

Image 2 (how it should look):
<img src="https://github.com/hlxsites/vg-roadchoice-com/assets/139977780/c9fe8270-5e5a-401c-bf4c-efa2b21f35b3" width="200px">

### Acceptance Criteria
- [x] The lowercase g uses the glyph shown in image 2.

**Comment by Gonzalo-CG** [comment]
Waiting on @Kannan-CM's input on how this was solved in the past.

**Comment by manuel-vara** [comment]
Hi @Kannan-CM , any news about this one?

**Comment by ZoeBeykirch** [comment]
The G letter looks correct, but now the fonts that were correct before are negatively impacted. Some letters are lower case, and some are upper-case mixed together and do not seem to be the same size as seen in screen shots below. 
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125895595/778deacc-1225-4099-954e-84c19d51baa3)
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125895595/e3c7d830-3a35-49a6-8dbb-f28a08aa3644)
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125895595/09bb7486-98f7-498c-8ace-58ba1d777536)

**Comment by manuel-vara** [comment]
FYI @SantiagoHomps-NC

**Comment by manuel-vara** [comment]
@girishdigrajkar can you test that too, please?

**Comment by SantiagoHomps-NC** [comment]
@ZoeBeykirch could you specify in which browser/version/OS are you having this issue? I tested in Brave, Chrome, Safari and Firefox and I'm not seeing this issue

**Comment by ZoeBeykirch** [comment]
No longer seeing this issue now, thank you for the quick fix!

**Comment by girishdigrajkar** [comment]
validated on WinOS (Edge, Firefox, Chrome) as well as MacOS (Chrome, Safari ) and able to get the correct results hence, marking the defect to done
