### ISSUE TITLE
Bug Medium: re-create Breadcrumb path using main category instead of non existing 'part-category' path

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-roadchoice-com#160]

**Comment by girishdigrajkar** [comment]
Validated and now upto level 3 breadcrumbs it works fine however, on PDP with level 4 breadcrumbs, getting 404 page error hence, reopening this bug:

e.g. https://160-re-create-breadcrumb--vg-roadchoice-com--hlxsites.hlx.page/parts?category=grilles&sku=GRL91201

Click on Grilles and 404 page is displayed:
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/110764da-ef2b-4995-82b2-0f199bf54702)

**Comment by manuel-vara** [comment]
@girishdigrajkar :  is this a content issue of a few categories or happening for all categories?

**Comment by girishdigrajkar** [comment]
@manuel-vara : @jonatan-lledo-netcentric and myself had a sync up call for this and it is happening for all 4th level breadcrumbs.

**Comment by girishdigrajkar** [comment]
Validated and now able to get the correct result as fourth breadcrumb navogates to correct page hence, marking the defect to done status.
