### ISSUE TITLE
Bug Medium: Fix sitemap.xml url path

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-roadchoice-com#166]
<img width="853" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/116451851/058116a2-bc73-407b-a934-8e526f32dcf2">

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, marking the defect to done status:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/4e3a17d9-5334-467f-821e-601d762a3c02">
