### ISSUE TITLE
Bug: Medium: Mobile/Tablet:  Blog/ Buses links navigates to 404 page 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#173]
**Steps:**
1. On Mobile Viewport (iOS/Safari,  Android/Chrome) or Tablet viewport 
  Navigate to https://main--vg-roadchoice-com--hlxsites.hlx.page/
2. Click on navigation hamburger icon 
3.  Click on Blog / Buses link and validate

**Expected vs Actual:**
404 page is displayed 

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/d723dd65-55fa-4b40-a18c-2cd5c3befe1d)

**Comment by jonatan-lledo-netcentric** [comment]
content issue, nav file updated @girishdigrajkar

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct result hence, marking the bug to done status.
