### ISSUE TITLE
Bug: Medium: after press back in the browser, the search doesn't clean up

### ISSUE THREAD

**Issue by jonatan-lledo-netcentric** [hlxsites/vg-roadchoice-com#178]
after a search, if the user presses back in the browser, the search page doesn't clean the session storage
this is how it looks the window
<img width="1365" alt="Screenshot 2023-10-18 at 15 14 53" src="https://github.com/hlxsites/vg-roadchoice-com/assets/117984204/e4b5f457-4233-4748-ae87-3bfcbdb77144">

and this is what it has the session storage
![Screenshot 2023-10-18 at 15 16 44](https://github.com/hlxsites/vg-roadchoice-com/assets/117984204/ecf8e43d-7b34-44b1-89ca-44eb3ad605f5)

**Comment by girishdigrajkar** [comment]
Validated and able to get correct results hence, marking the defect to done.
