### ISSUE TITLE
Modify favicon

### ISSUE THREAD

**Issue by SantiagoHomps-NC** [hlxsites/vg-roadchoice-com#185]
<img width="124" alt="Screenshot 2023-10-23 at 10 31 18" src="https://github.com/hlxsites/vg-roadchoice-com/assets/103571932/869f70db-f351-475c-b484-0d831fa83c2f">

**Comment by girishdigrajkar** [comment]
Validated in OS browser combinations and able to get the correct results hence, marking the defect to done status.
