### ISSUE TITLE
Bug: Critical - Bumper filters are not loading all result options

### ISSUE THREAD

**Issue by SantiagoHomps-NC** [hlxsites/vg-roadchoice-com#204]
To fix misplaced [ISSUE](https://github.com/hlxsites/vg-macktrucks-com/issues/492) #492

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/36c17123-defc-4799-8d58-a4e5616039a1">
