### ISSUE TITLE
FIX google logo on dealer locator

### ISSUE THREAD

**Issue by SantiagoHomps-NC** [hlxsites/vg-roadchoice-com#217]
Add logo and information on the the dealer locator's map

**Comment by girishdigrajkar** [comment]
Validated and able to see expected results hence, marking this ticket to done status

<img width="1792" alt="Screenshot 2023-11-16 at 12 24 03 PM" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/90fde7c0-9363-452d-9ab9-8357add694ec">

<img width="1772" alt="Screenshot 2023-11-16 at 1 29 55 PM" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/db63af20-99fb-478e-970b-2e15a26db85c">
.
