### ISSUE TITLE
Bug: "Filters" is not showing the options for select products

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-roadchoice-com#230]
**URL**
https://www.roadchoice.com/

**Steps to replicate**
- Go to Categories
- Click the down arrow to reveal the dropdown
- Select Wheel Seals - https://www.roadchoice.com/part-category/?category=wheel-seals
- View the Filters on the page

**Expected results**
All the filters available for the selected product are shown

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/126615590/8f6f0c62-6877-45b9-8b69-fe5208ee7442)

**Actual results**
The filters box is either limited or not shown

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/126615590/d74459a0-32e5-456d-8895-3a57b89b0e03)

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/126615590/d9e1620d-e2e8-432f-9e2d-c1981a34dae5)

**Comment by BeckyMedlin** [comment]
@mollyaljenkins @verareljic This bug may be related to https://github.com/hlxsites/vg-roadchoice-com/issues/229
