### ISSUE TITLE
FR: [Columns] - Roadchoice Block

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-roadchoice-com#236]
### Context/Description

As a Road Choice content author, I want to have a columns block on my website so that I can alternate images and text on within the same page seamlessly so that I can improve the user experience. 

### Acceptance Criteria

**User AC:**
- As a website user, I can see images and text side by side. 

**Editor AC:**
- As an editor, I am able to create more visually appealing pages with a mix of images and text without needing to build new components from scratch. 
- I can find and use this block in my AEM Sidekick library. 
- I can use this block on any page. 

**Non-functional AC:**
- The block should match the Road Choice brand guidelines for CSS style sheet including colors, fonts, etc.
- All functionality how users interact with the columns block including reverse odd rows on mobile shall be the same as the Volvo Trucks website on desktop, tablet and mobile devices. 

### Attachment / link to Figma

Examples: 
https://www.volvotrucks.us/parts-and-services/parts/partsasist/
https://www.volvotrucks.us/trucks/powertrain/i-torque/

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/125895595/d178d965-71cc-4489-aeb8-4fcf386280bf)

**Comment by girishdigrajkar** [comment]
Observation :
1.  **Sequence of image/text is incorrect in case of mobile viewport:**
If image is on left and text on right then on mobile viewport. image comes first and then text
Whereas, when image is on right and text on left then, on mobile viewport text is displayed first followed by image ...
It happens correctly in case of reference URL mentioned in ticket https://www.volvotrucks.us/parts-and-services/parts/partsasist/

however,  on https://236-columns--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/media-with-text the sequence is image first and text later which is not in sync with whats mentioned as expectation in User story

2. top margin is not available in the block, it should be 48px.

**Comment by BeckyMedlin** [comment]
@santi-homps Is this item still blocked?

**Comment by girishdigrajkar** [comment]
Branch URL is resulting in 404 error now, Please have a look and park it for testing as soon as done  : 

<img width="1599" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/837b15f4-76b0-4a37-8530-38d8e98ab808">

**Comment by santi-homps** [comment]
@girishdigrajkar Post discussion with @ZoeBeykirch this issue can be closed since this behaviour is as expected.
