### ISSUE TITLE
FR: Duel Search Navigation Bar 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-roadchoice-com#25]
Road Choice requires duel a search for Cross-Reference Number and Part Number. 

1. Cross Reference Number is powered by the following [excel document](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-roadchoice-com/cross-reference-data/[road-choice-cross-reference-data-july12.xlsx](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-roadchoice-com/cross-reference-data/road-choice-cross-reference-data-july12.xlsx?d=w5680414535be4421ac16b4dc4c955bb2&csf=1&web=1&e=oLKicZ)?d=w5680414535be4421ac16b4dc4c955bb2&csf=1&web=1&e=oLKicZ ): 

2. The part number search is powered by the individual part category files [here](https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000FF16C1F85E2B3849A4CD207A7190B18C&id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2FVolvoGroup%2Fvg%2Droadchoice%2Dcom%2Fproduct%2Ddata&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95). If the user selects Part Number search, then a Make and Model filter should appear. The user must first select the Make for the Model to be able to be populated. The options for Make should be in the following order in a drop-down list: Make (All), Autocar, Ford, Freightliner, Hino, International, Kenworth, Mack, Navistar, Peterbilt, Sterling Truck, Volvo, Western Stars, Others

3. We would like to improve the UX of the search bar design while keeping all of the existing functionality there is today on the live site to the following designs. 
[roadchoice.pdf](https://github.com/hlxsites/vg-roadchoice-com/files/12029539/roadchoice.pdf)

**Comment by jonatan-lledo-netcentric** [comment]
I suggest this can be added as is the sub-nav on the other domains, but in the normal flow of the page, so it won't need to be implemented on every page as a regular block.

**Comment by girishdigrajkar** [comment]
**Test summary:**
1.  Validated for **Cross Reference Number** for which road-choice-cross-reference-data-july12.xlsx file on sharepoint is referred by the code and correct data is being pulled in session : **PASS**

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/f82e32be-fafa-4a5f-ba90-170462416a77">

2.  Need more details :  On hold.    
3.   Validated as per design and is as expected (  Additional info: Joe has approved spacing between the menu 'cross reference number' & 'Part number' ) : **PASS** ( Except the minor bug #83 )

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/b56a2901-16ab-4de9-bed6-6d1ac87f0844">

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/80cd1fc6-eb80-421c-8bd1-ccc75af8abc6">


cc: @jonatan-lledo-netcentric, @SantiagoHomps-NC

**Comment by girishdigrajkar** [comment]
Since the file references are incorrect, parking this ticket to in development for changes.
Please assign it back to QA once changes are done. Thanks.

**Comment by jonatan-lledo-netcentric** [comment]
is a bit confusing having this feature ticket as "bug in development" if this is a feature ticket, not a bug one. please @girishdigrajkar , create its own ticket and link this one as reference. thanks

**Comment by shirin27** [comment]
@jonatan-lledo-netcentric I put it back to in dev, seems QA is expecting some changes 😄

**Comment by girishdigrajkar** [comment]
Validated #25 & #43  i.e.search functionality and below is the status:
Testing completed with below outstanding issues which will be retested separately post the fix:

Major defects >>  #104,  #107,  #108 &  #109   
Minor defect >> #110
