### ISSUE TITLE
Bug: Medium: New tab is not displayed when user clicks on FAQ link

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#26]
Steps:
1. Navigate to https://17-footer--vg-roadchoice-com--hlxsites.hlx.page/
2. Click on FAQ link in Footer

Expected vs Actual:
The FAQ page should opened in new tab however, it opens the page in same tab

**Comment by SantiagoHomps-NC** [comment]
The thing is we dont have this pages created, but its going to the correct URL

**Comment by girishdigrajkar** [comment]
Issue persists; Reopening the bug.

**Comment by SantiagoHomps-NC** [comment]
Fixed in PR #28  [HERE](https://github.com/hlxsites/vg-roadchoice-com/pull/28)

Already merged, check in: https://main--vg-roadchoice-com--hlxsites.hlx.page/

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct result hence, closing the bug.


![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/5d31f76a-bd6a-48ec-aab5-15ecec4e6944)
