### ISSUE TITLE
FR: Hero Block (1 of 2)

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-roadchoice-com#262]
### Context/Description

As a Road Choice website content editor, I want to add a hero block to my website pages so that I can enhance the user experience with compelling images and clear call-to-actions, enabling users to quickly grasp the key offerings and value propositions of the site.

### Acceptance Criteria

**Editor AC:**
- [ ] As an editor, I can find this block in the AEM Sidekick library
- [ ] As an editor, I can customize the hero image, heading and sub-heading text, and/or button CTA and link.

**Non-functional AC:**
- [ ] Hero block image dimension shall follow a 16:9 ratio 
- [ ] Hero block shall be full width 
- [ ] Hero block shall be responsive to adjust to any device
- [ ] Text on hero shall be centered and white color. 
- [ ] The heading text displayed on the first line shall be H1 size 
- [ ] The sub-heading text displayed on the second line shall be H3 size and shall extend to another line after roughly 30 characters.  
- [ ] A button can be added under the text that is red color #B92530 and centered. 
- [ ] Header, sub-text, button, image are all configurable

### Note

MT standard hero code to be reused (preferred style over VT hero)

Once this ticket is completed, then https://github.com/hlxsites/vg-roadchoice-com/issues/238 can be picked up. 

### Attachment / link to Figma
Note - Figma is a high level example for guidance, and it doesn't have the correct font. The Road Choice CSS font styles should be applied. 
https://www.figma.com/design/dvfiihEoJvFVMvxSDPVjfR/Untitled?node-id=3-3791&t=ARlLxwnMmS9Wsdwf-1

![Image](https://github.com/user-attachments/assets/6b0e65dd-6b24-4a5f-8441-822362345ee5)

**Comment by AsmitKMishra** [comment]
Testing Completed. Feature works as excepted and fulfills the requirements.

**Comment by santi-homps** [comment]
This block was merged into RC's aem repository
