### ISSUE TITLE
Bug: Minor: Roadchoice footer has minor differences in social media icons

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#29]
Steps:
Navigate to https://17-footer--vg-roadchoice-com--hlxsites.hlx.page/
Validate the social media icons

Expected vs Actual :
Difference in social media icons of facebook and linkdIn are noted:

<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/77ae2f89-a5d5-4a7c-9a25-1c9500837832">

**Comment by SantiagoHomps-NC** [comment]
@girishdigrajkar is it solved in #98 ?

**Comment by girishdigrajkar** [comment]
@SantiagoHomps-NC : LinkedIn logo is incorrect as does not have white background except it all logos are fine.

**Comment by girishdigrajkar** [comment]
Validated and the LinkdIn logo is not as expected as missing white background. Reopening the bug.
