### ISSUE TITLE
FR: Dealer locator block for RoadChoice

### ISSUE THREAD

**Issue by verareljic** [hlxsites/vg-roadchoice-com#3]
- copy the dealer locator block from macktruck.com
- adjust styling to fit RoadChoice.com

![Image](https://user-images.githubusercontent.com/135319298/249534294-d399745e-618e-43b7-81d5-14c7728be238.png)

**Comment by girishdigrajkar** [comment]
Testing has been completed and below are the active defects,  Major defect is outstanding so marking this ticket to on hold status:

#61 (Major) , #69 (Medium) , #48 (Minor)
