### ISSUE TITLE
Bug: Major: Mobile:  Carousal slider halts at 3rd slide in case of mobile; works fine in desktop

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#32]
Steps:
1. In mobile view port, Navigate to https://5-slider--vg-roadchoice-com--hlxsites.hlx.page/drafts/tdziezyk/carousel
2. Validate the Carousal

Expected vs Actual:
 1. Carousal slider halts at 3rd slide in case of mobile; works fine in desktop
 2. Unable to click on 4th slider "carousel-controls-pagination-step carousel-controls-pagination-step" 
 
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/68159b1d-c0d7-4422-b856-ae621988275e">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/e9fbf67a-dc9e-41dc-a442-771d1eaa2b9e">

**Comment by jonatan-lledo-netcentric** [comment]
tested in my Chrome and Firefox and it works for me

**Comment by girishdigrajkar** [comment]
Validated in browserstack > iphone 13 pro max > chrome browser and able to get the correct results; on mobile viewport it is still reproducible on desktop device however, could be ignored as per browser stack results hence, closing the bug.
