### ISSUE TITLE
Bug: Major: The fonts of Carousal block are not as expected 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#33]
Steps:
1. Navigate to https://5-slider--vg-roadchoice-com--hlxsites.hlx.page/drafts/tdziezyk/carousel
2. Validate the fonts of text/Labels displayed on Carousal block

Expected:
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/b1965f8d-ea5d-464b-9826-8b3e5c7275e7">

Actual:
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/689688e4-b93e-4fc3-8d69-9e55f7ce5142">

**Comment by jonatan-lledo-netcentric** [comment]
this is just test content. the main page is not ready yet

**Comment by girishdigrajkar** [comment]
Reopening the bug as font for 'Carousal-heading' class i.e. carousal heading is correct for both desktop & mobile viewport however, the font for the title of  link in 'button-container' class is incorrect in both desktop and mobile.

Expected is 19px in mobile viewport & 52px in desktop : 
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/3bbd6d1f-c4ed-4f88-9734-eb8fc5bbf66a">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/a3339e90-b755-433e-9945-e4652affc3a0">

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed;
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/3612dc1f-f7cc-4725-a1f0-eca4f32c2baf">
