### ISSUE TITLE
FR: Setup the Franklin Library for RoadChoice

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-roadchoice-com#34]
**Description:**

As an editor, I want to have a library of blocks available for me when editing pages for RoadChoice.com, to easily add new blocks to the page, with default content to guide me.

**Acceptance criteria:**

- The Library is available to content authors via the AEM sidekick toolbar
- The Library includes all the blocks available for RoadChoice

**Comment by girishdigrajkar** [comment]
Validated and able to see the blocks library however, not all blocks are available as block development is still ongoing:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/38f09bb9-9cd8-43b5-a7e7-eb00cd4b3801">

**Comment by Gonzalo-CG** [comment]
### Updated Acceptance criteria:

- [ ] The Library is available to content authors via the AEM sidekick toolbar.

---

Adding all the blocks to the library will be taken care of on issue #143 

FYI @girishdigrajkar

**Comment by girishdigrajkar** [comment]
Based on above comments of revised scope within this ticket, marking this ticket to done.
