### ISSUE TITLE
FR: 404 page

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-roadchoice-com#35]
<img width="1657" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/116451851/875edb68-ebf3-4232-a09b-02f0d44d3f86">

**Comment by shirin27** [comment]
Dependancy with https://github.com/hlxsites/vg-roadchoice-com/issues/25.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, marking this ticket to done.
