### ISSUE TITLE
FR: Subcategory Template: Product listing with Card Dynamic Data

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-roadchoice-com#36]

**Comment by shirin27** [comment]
**Description**

Example of product listing: https://roadchoice.com/part-category/antennas

**Data mapping:**

Datasource: https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BA074844C-8A58-4FD4-B71E-64D56A62D06F%7D&file=rc-batteries.xlsx&action=default&mobileredirect=true

**Title**: 27CRC (Base Part Number) Road Choice Group 27 Battery (Part Name ?? -> in the file, name is _Road Choice **Series** 27 Battery_) 
**Subtitle**: Part number (fixed label): 27CRC (Base Part Number) 

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/1f98b64e-40f8-4f00-b794-9a494b3ecbfd)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking the ticket to done status:

**Product data path :** https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?e=5%3Acc25ecdd657e4de690d68b5624830d7c&at=9&FolderCTID=0x012000FF16C1F85E2B3849A4CD207A7190B18C&id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2FVolvoGroup%2Fvg%2Droadchoice%2Dcom%2Fproduct%2Ddata&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/d607bf37-29fb-4179-8e40-755db1287b42">
