### ISSUE TITLE
FR: Subcategory Template: Filter By Product Property Block

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-roadchoice-com#37]

**Comment by shirin27** [comment]
**Description**

Example of page with filters: https://roadchoice.com/part-category/batteries

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/060dd18e-9a49-4fa3-8d75-fc89427fe099)

- Use cases:
1. Choosing multiple options from the same filter type applies an "OR" operator to the list of products (ex. https://roadchoice.com/part-category/batteries?f=terminal_type%3DPost%7COR%7CStud)
3. Choosing options from different filter types applies an "AND" operator to the list of products (ex. https://roadchoice.com/part-category/batteries?f=terminal_type%3DStud%26reserve_capacity%3D100)

- Query input is added as a search parameter to the URL (ex. ?f=terminal_type%3DStud%26reserve_capacity%3D100)

**Data source**
- Data comes from the product category file (example: https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BA074844C-8A58-4FD4-B71E-64D56A62D06F%7D&file=rc-batteries.xlsx&action=default&mobileredirect=true)
- **Open point**: How is it determined which columns to show as filters? Is it a fixed list?

**Comment by manuel-vara** [comment]
> * **Open point**: How is it determined which columns to show as filters? Is it a fixed list?
It is not a fixed list, it's a dynamic list that depends on properties of each category, so each product that belongs to this category will have same set of properties. Therefore, looping through the JSON structure would be required to render that list of properties
