### ISSUE TITLE
FR: PDP Template: Product Details Block

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-roadchoice-com#39]

**Comment by shirin27** [comment]
**Description**

**Product information table:**
- Based on the data in the product category table (ex. https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B56F82E5F-685A-4382-AC99-6BE10EC00F54%7D&file=rc-alternators.xlsx&action=default&mobileredirect=true)

- Example of info displayed for ALT8329 (no processing; displayed as is):

Volts : 12
Amps : 160
Mount Type : J180 Mod
Rotation Type : Bi-Directional
Pulley Grooves : No Pulley
Brush Type : Brush-Type
Remote Sense Terminal : No
Ground Terminal : 1
B+ Terminal : 5/16
R Terminal : #10
Weight (kg) : 9.53 
Warranty : 36-months, no cores 

**Product images:**
- Based on the data in the product image table (ex. https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BC7A542F2-9ED6-4195-BA84-FDB5592EE398%7D&file=rc-product-images.xlsx&action=default&mobileredirect=true)
- Image matched with product via part number

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/8f578ae5-e597-4b83-b275-aa26a7c3f012)

**Comment by shirin27** [comment]
Will be done in #77
