### ISSUE TITLE
FR: PDP Template: Related Blog posts Block

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-roadchoice-com#41]
<img width="1534" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/116451851/9966fa01-0b1f-4692-bf23-6a99698a557b">

**Comment by shirin27** [comment]
Data source will be existing content, tagged with the proper category, and on products from that specific category we will display the content based on those tags.

Title of the page
Published date
Description (metadata of the page)
Read more - URL to the page

**Comment by shirin27** [comment]
**Blocker**: source of data for categories to be cleaned up

**Comment by BeckyMedlin** [comment]
@janedbarra Has the category data source been cleaned up yet?

**Comment by janedbarra** [comment]
Are you needing a list of blog articles and what product category they are relevant to? I am unsure of the ask.

**Comment by BeckyMedlin** [comment]
@shirin27 Please clarify the issue regarding the data source for @janedbarra.

**Comment by girishdigrajkar** [comment]
Validated and able to get correct results except for multi tag data for which #122 defect is active.

Closing this ticket as bug will be tested separately.

**Comment by girishdigrajkar** [comment]
Validated and able to get correct results except for multi tag data for which https://github.com/hlxsites/vg-roadchoice-com/issues/122 defect is active.

Closing this ticket as bug will be tested separately.
