### ISSUE TITLE
Bug: Medium: Nav menu has incorrect contrast set for few sub menu links & the menu order is also not correct

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#42]
Steps:
1. Navigate to  https://6-header-and-nav-block--vg-roadchoice-com--hlxsites.hlx.page/
2. Click on CATEGORIES and verify the menu order
3. Validate the color contrast set for the sub menu link
4. Verify the 'CHEMICALS AND LUBRICANTS' sub menu DEF

Expected :
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/5863d675-87af-424f-a10f-0633b6f2fdde">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/78669140-d0da-4182-818b-f4330f65e650">

Actual:
1.  SUB Menu order is not correct for the CATEGORIES menu
2.  menu has incorrect contrast set for few sub menu links
3. DEF / DEF Equipment sub menus are shown as **Def** / **Def Equipment** incorrectly.
4. few sub menu link names are on multiple lines unlike expected on single line
5."Poly Torque Rods" sub menu missing from 'SUSPENSION' menu
6. Menus like 'CATEGORIES' has font size 18px whereas, expected is 17px 

<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/eaa6f741-e644-478c-a3bf-b3684c84b593">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/71cdec7f-ce67-431f-9840-b3e28b5d3b01">

**Comment by jonatan-lledo-netcentric** [comment]
@girishdigrajkar I updated the _nav_ document file because I removed all 4th-level links, but I can also update the CSS file to remove the styles for that nav level

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking the bug to done status.
