### ISSUE TITLE
FR: [RoadChoice] Cards variant for RoadChoice.com

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-roadchoice-com#44]
**Description**

On the production [Resources page](https://roadchoice.com/resources), there is a cards list to show the different resources available on the website.
The goal of this ticket is to implement a card variant for road choice, in the brand styling, to be used in this context.
The card should allow the addition of an svg of a png with transparent bg.

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/9f854fed-a86d-4886-a320-708640599c60)

**Acceptance criteria**
- The card variant for RoadChoice is styled as per brand's design (colour scheme / font)
- The block allows editors to add an svg or a png with transparent bg and a text
- On smaller viewports, 2-cols should change to 1-col

**Comment by girishdigrajkar** [comment]
Validated and defects #89 & #90 are outstanding and hence,  marking this ticket to on hold.
