### ISSUE TITLE
Bug: Minor: Mobile : The space in between title 'Where to buy' is more & text spans on 4 lines instead of 3lines

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#49]
Steps:
Navigate to https://4-find-dealer-block--vg-roadchoice-com--hlxsites.hlx.page/
Validate the 'find a dealer' block

Expected vas Actual:
The space in between title 'Where to buy' is more & text spans on 4 lines instead of 3lines

<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/402861bc-42cf-4972-85b7-3da6080332f4">

**Comment by ZoeBeykirch** [comment]
Closing as this is fixed.
