### ISSUE TITLE
FR: Carousel Block for RoadChoice

### ISSUE THREAD

**Issue by verareljic** [hlxsites/vg-roadchoice-com#5]
- Copy the carousel block from macktrucks.com
- Adjust the styling to match roadchoice.com

![Image](https://user-images.githubusercontent.com/135319298/249533461-c722abd4-dcd8-4c8f-8930-78c2bbc713be.png)

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd @girishdigrajkar The related defects have been closed. Can this one be taken off hold and tested now?

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd This one looks like it's on hold, but it's been closed. Please update the status.

**Comment by DanielaPedrochevd** [comment]
@Gonzalo-CG please check last comment :)
