### ISSUE TITLE
Bug: Medium: Font & block height difference observed for the breadcrumb/blog article template 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#53]
Steps:
1. Navigate to  https://2-blog--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/blog/road-choice-steel-wheels-budget-friendly-and-built-strong
2.  validate the breadcrumb/ blog article template block height and font.

Expected:
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/6856cdf1-e2cf-4dd4-b128-fa7f3d7d6e9c">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/e84e616f-7f25-4bcd-9b88-28ccc8687292">

Actual:
Font & block height difference observed for the blog article template :
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/f5cf480b-8995-418d-8105-69c815d55ec6">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/e336f7bf-569f-489d-8781-84bda2ef9068">

**Comment by ZoeBeykirch** [comment]
Closing ticket as it's no longer needed.
