### ISSUE TITLE
Bug: Medium: Blog article block has incorrect font for field-title, blog date & link color is not as expected

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#54]
Steps:
1. Navigate to https://2-blog--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/blog/road-choice-steel-wheels-budget-friendly-and-built-strong
2. Validate the field-title, blog date & link 

Expected:
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/b171a075-8a46-46a2-b9ed-05dc9e473e5c">

Link:
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/fa2e3fb2-4c83-4ee5-94a7-be72536420ce">

Actual:
For desktop port h1.artical-title has font size of 52px whereas, expected size is 50px;  For mobile port it is 35px whereas, expected is 28px.
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/06099531-3d67-43f0-8b08-d91ec3e2fc4e">

For both desktop & mobile port field-published i.e. blog date has 14px whereas, expected size is 16px. 
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/80053793-5dd5-4dee-88d6-22b232b233f5">

Link in blog has different color than expected:
<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/fec97300-5977-46d4-a23f-4e911d275770">

**Comment by SantiagoHomps-NC** [comment]
@girishdigrajkar  Please re-check on this route:
https://main--vg-roadchoice-com--hlxsites.hlx.page/blog/stop-prepare-save-money-brake-safety
Font size differences are due to a generalization on the whole site.

**Comment by girishdigrajkar** [comment]
Based on above comments marking the bug to done as no action will be taken.
