### ISSUE TITLE
FR: [RoadChoice] PDP: Part fit section enhancement

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-roadchoice-com#55]
**Description**:

**Today**, the section for checking if a part fits my vehicle is presented in the form of a table, however, there is usually only one fitting vehicle.
Related to #77 

https://roadchoice.com/parts/bumer000052
https://roadchoice.com/parts/rad37403p

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/5b1c484f-670c-4ce5-8d37-756c8a57fa3a)

**Tomorrow**, the section is presented in the form of a card:
**Decision**: Option 2

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/d9a8ccd9-9393-47dc-873d-3515d7b370a0)

**Specifications**
[AF Block: Part fit section](https://projects.netcentric.biz/wiki/display/VOLVOFN/AF+Block%3A+Part+fit+section)

**Acceptance criteria**

**Open points**
- Data source sample to be added to our test data
- Separate files per categories; to be provided by Jane B. on SharePoint.
- To be discussed if there will be different files or only one -> we would prefer one file.
- Model description - to check the current data on this; possibly to be removed; usually it should be a short text.

Figma for new UX: https://www.figma.com/file/6bHOxjYFCkseuztuTch5pv/roadchoice?type=design&node-id=0%3A1&mode=design&t=zKzqpBsWOpMG4SUc-1

**Comment by BeckyMedlin** [comment]
@ZoeBeykirch Please add the designs here. Thank you!

**Comment by ZoeBeykirch** [comment]
https://www.figma.com/file/6bHOxjYFCkseuztuTch5pv/roadchoice?type=design&node-id=0%3A1&mode=design&t=zKzqpBsWOpMG4SUc-1

**Comment by girishdigrajkar** [comment]
Validated and able to get correct results except for below bugs which will be tracked separately hence, closing this ticket:

#[134](https://github.com/hlxsites/vg-roadchoice-com/issues/134)
#[133](https://github.com/hlxsites/vg-roadchoice-com/issues/133)
