### ISSUE TITLE
FR: [RoadChoice] Inject the artibot chatbot script

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-roadchoice-com#58]
**Description**

- As part of the current website migration, implementing the artibot chatbot is also required:

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/f9a1b9f6-4209-463a-80d1-dbd5134176de)

**API**: https://api.artibot.ai/api/bots/8b46bd2b-302c-418e-9d5a-b1c46088754f/chats/init/fab0bc96-7868-46a6-a1e0-3c6ca432f068

**Acceptance criteria**
- Same behaviour of the chatbot as on the current website roadchoice.com applies
- Cookie consent would impact the rendition of the chatbot:
- - If cookies are not accepted, the chatbot would not be rendered (see open points for the category of cookies that would block this)

**Open points**
- Which category of cookies would block the artibot from being displayed? - not needed, artibot is not collecting data

**Comment by manuel-vara** [comment]
Artibot script provided in their integration instrructions:
<script type="text/javascript">!function(t,e){t.artibotApi={l:[],t:[],on:function(){this.l.push(arguments)},trigger:function(){this.t.push(arguments)}};var a=!1,i=e.createElement("script");i.async=!0,i.type="text/javascript",i.src="https://app.artibot.ai/loader.js",e.getElementsByTagName("head").item(0).appendChild(i),i.onreadystatechange=i.onload=function(){if(!(a||this.readyState&&"loaded"!=this.readyState&&"complete"!=this.readyState)){new window.ArtiBot({i:"8b46bd2b-302c-418e-9d5a-b1c46088754f"});a=!0}}}(window,document);</script>

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG @manuel-vara What is needed to resolve this ticket? Can we get it planned for a future sprint or added to the backlog?

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG @manuel-vara Please advise on next steps. This ticket is in a closed sprint, but is unresolved. Thanks!

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking the ticket to done :

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/ae0727b6-ec4e-43cb-946e-75e2ba6a4885">
