### ISSUE TITLE
NFR: Dealer Locator: Solution design to improve Dealers data loading/rendering times

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-roadchoice-com#59]
As we have 2 urls to get all dealers data from both brands (Volvo and Mack) loading times are currently quite long (around 45 seconds or more).
This issue is explore a solution that can improve the loading times of the list of dealers.
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/116451851/f2261e8a-950e-48ef-80f3-db7e90d6a426)

**Comment by shirin27** [comment]
To decide if this ticket is needed, we need to wait for an alignment with Volvo internal team responsible for dealer data, who might provide another endpoint that could offer faster responses.

**Comment by BeckyMedlin** [comment]
@Joesturbo @DanielaPedrochevd This one appears to be dependent on https://github.com/hlxsites/vg-roadchoice-com/issues/97 Should it be moved into the backlog?

**Comment by DanielaPedrochevd** [comment]
@Gonzalo-CG please check last comment :)

**Comment by Gonzalo-CG** [comment]
@BeckyMedlin This one is on hold until we have the POD API available.

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG Let's get this one moved to the backlog for a future sprint (after POD API implementation).

**Comment by DanielaPedrochevd** [comment]
Blocked until we have the POD API available.

**Comment by BeckyMedlin** [comment]
Dependent on https://github.com/hlxsites/vg-roadchoice-com/issues/97

**Comment by ZoeBeykirch** [comment]
Closing ticket as dealer locator loading has been improved.
