### ISSUE TITLE
Bug: Major: Few dealers are not showcased on find a dealer map and the dealers  results

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#61]
Steps:
1. navigate to https://3-dealer-locator-block--vg-roadchoice-com--hlxsites.hlx.page/
2.  Go to find a dealer block enter 'New York' and click on magnifier glass icon/hit enter on keyboard
3.  Wait to get the results loaded on the displayed page 
4. Click on 'Certified Electric Dealer'

Expected vas Actual:
Less dealer results are shown :

<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/44847592-7050-47ac-bd79-a01f94d1d80c">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/848c8b14-9c74-44d5-bfa0-03e6f31950db">

**Comment by jonatan-lledo-netcentric** [comment]
I already saw it but it seems they are duplicated

**Comment by shirin27** [comment]
to be solved for go live

**Comment by BeckyMedlin** [comment]
@manuel-vara Dealer Locator needs to leverage the Dealer POD. Please advise when that work can be scheduled in a sprint as it may resolve this issue.

**Comment by Gonzalo-CG** [comment]
Waiting on #97

**Comment by shirin27** [comment]
Can be worked once we implement the dealer pod integration in #97

**Comment by BeckyMedlin** [comment]
@girishdigrajkar Now that the Road Choice Dealer POD data is in production, please verify if this remains a problem. Thank you!

**Comment by girishdigrajkar** [comment]
Validated post issue #97 resolution ,  Able to see correct dealers displayed successfully : 

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/1473304a-91b1-499b-b154-f66cc8306dc8)
