### ISSUE TITLE
Bug: Major: Firefox:  page is blank except for the header for roadchoice

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#63]
Steps:
1. Navigate to https://3-dealer-locator-block--vg-roadchoice-com--hlxsites.hlx.page/ using firefox browser
2. Validate the page 

Expected vs Actual:
page is blank except for the header when opened in firefox browser whereas, it should open correctly

**Comment by jonatan-lledo-netcentric** [comment]
this issue also fixes an aesthetic issue with the carousel block
<img width="118" alt="Screenshot 2023-08-02 at 09 07 30" src="https://github.com/hlxsites/vg-roadchoice-com/assets/117984204/5eabd1b4-b301-4ec6-aa41-d349e2c3ede5">

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed;

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/240cfb2b-4352-4e5f-ba94-28e30909084d">
