### ISSUE TITLE
FR: [Roadchoice] PDP: Related Catalogs, Products Sheets, eCatalogs and more Block

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-roadchoice-com#65]
**Description**
Example of PDP with the section: https://roadchoice.com/parts/27crc
Related to #77 

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/165e1fbe-1f28-4624-9f7f-52f6a42e9493)

**Data mapping**
Data source to be linked to the ticket -> https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B6CCD90DD-AA02-4E7E-BABA-C15B034836BD%7D&file=catalogs-categories.xlsx&action=default&mobileredirect=true
**Acceptance criteria**
- The related catalogs, product sheets, ecatalogs and more section is displayed in an accordion
- The title and description are the same across different categories
- The table with resources is different, according to the category of the product
- When clicking on the link of the resource, the PDF is opened in a new tab

**Comment by BeckyMedlin** [comment]
@SantiagoHomps-NC Is this work complete or in progress? Possibly a duplicate?

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results as per AC mentioned in ticket description :
Marking this ticket to **done** as all checks **except the medium defect #121**  are passed.

**Additional check :** The category (e.g. Batteries) & Type in [source excel](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B7682F59E-14E0-4DF1-B0B0-FA625776E376%7D&file=catalogs-categories.xlsx&action=default&mobileredirect=true) is case insensitive & leading or trailing spaces in category / type columns data does not affect the functionality.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/7967f082-d75c-4d11-b49d-64cf1e651b6f">

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/b22b05f2-f7d2-4b58-b608-aa72a6c8f369)
