### ISSUE TITLE
FR: [Roadchoice]: PDP: Related Safety Data Sheets Block

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-roadchoice-com#66]
**Description**
Example of PDP with the section: https://roadchoice.com/parts/27crc
Related to #77 

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/092074c9-13c4-4e2e-8df9-69367170f187)

**Data mapping**
Data source to be linked to the ticket -> https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B58069ECE-5409-47D2-8ABD-6EC46BA05A5A%7D&file=sds-categories.xlsx&action=default&mobileredirect=true

**Acceptance criteria**

- The related SDS section is displayed in an accordion
- The title and description are the same across different categories
- The resources are different, according to the category of the product
- When clicking on the link of the resource, the PDF is opened in a new tab

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results as per AC mentioned in ticket description :
Marking this ticket to done

Additional check :  The category (e.g. Batteries) in [source excel](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B58069ECE-5409-47D2-8ABD-6EC46BA05A5A%7D&file=sds-categories.xlsx&action=default&mobileredirect=true) is case insensitive & leading or trailing spaces does not affect the functionality.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/25b1fbc6-51f3-4c47-a061-719a3b9dbba2">
