### ISSUE TITLE
Configuration of OneTrust consent and tag availability

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-roadchoice-com#72]
**Description**
Implement OneTrust Consent and loading tags per cookie type:

 **Performance cookies (Group 002):**
- GA
- Hotjar

**Targeting cookies (Group 004):**
- Pardot
- Artibot

_**Pre-requisites**: confirm cookie category for Pardot and Artibot._

**Acceptance criteria**
- Based on the cookie categories defined by business, the corresponding scripts are loaded or not in accordance to what the user accepts

**Out of scope**
Update of https://roadchoice.com/cookies based on cookie categories.

**Comment by manuel-vara** [comment]
@Kannan-CM , @Joesturbo is Pardot consent still required, I believe Pardot tracking was switched off on server-side, can you confirm, please?

**Comment by girishdigrajkar** [comment]
Confirmed with @manuel-vara , This defect will be only tested post go live so marking it to 'On hold' status.

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG Please move this one to the backlog for post go-live testing
