### ISSUE TITLE
Defect: Medium: The date format of blogs is incorrect for some blogs & 'FILTER BY BLOGS'  label is not displayed

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#75]
Steps:
1. Navigate to https://46-blog-results--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/blog/
2. Validate the Blog Results blog

Expected: 
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/2523a2a5-df58-4a77-a5fc-7171f5805839">

Actual:
1. 'FILTER BY BLOGS'  label is not displayed
2.  Date format is incorrect for some blog results as expected is 'MM/DD/YYYY' whereas, actual is 'DD/MM/YYYY'

<img width="1792" alt="Screenshot 2023-08-04 at 3 45 05 PM" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/3c0be8ed-0c60-4d55-8217-cc66339b90cb">

**Comment by jonatan-lledo-netcentric** [comment]
@girishdigrajkar please re-check the title in the main branch because is already fixed, not sure if the date is also fixed

**Comment by girishdigrajkar** [comment]
The title is displayed correctly;  The date format needs a fix: 

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/ac8127fa-d241-485a-97d0-e6e54f1ac54a)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results, marking the bug status to done :

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/162e0a82-f505-4ada-b6ec-4bde4dd77f1b">
