### ISSUE TITLE
FR: PDP template (dynamically created content)

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-roadchoice-com#77]
**User journey:**
The user uses the navigation, arrives to the product category page (subcategory) and accesses a product.
The content of the page is rendered based on the base part number (in case of product detail block) or subcategory (in case of the other sections)

**Current situation:**
The URL to the product page is formed of:
- Fixed part: https://roadchoice.com/parts/
- Part number: appended to each product

**Future situation:**
The URL to the product page is formed of:
- Fixed part: https://roadchoice.com/parts/
- Category (ex. Electrical)
- Subcategory (ex. Batteries)
- Base Part Number
_Ex. https://roadchoice.com/parts?category=batteries&sku=27crc_ (https://roadchoice.com/parts?category=:subcategory&sku=:productnumber)
- Based on the part number appended to the URL, we query the product details
- Breadcrumb is created based on the URL path HP > Category > Subcategory > Base Part Number

[Datasource](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BD98F331A-BB95-4DA4-8A9F-4BF6021BFF20%7D&file=RC_Batteries.xlsx&action=default&mobileredirect=true)

**Acceptance criteria:**
- This ticket is the follow up implementation ticket of #79 
- Clean up the code from #79 
- Render the product details in a table 
   - render the product image or images (if multiple images, show a gallery)
   - If no image show a placeholder Image

Ticket 2:
- Get the information based on the category, to be displayed in sections
  - Catalogs
    - divided by language
  - SDS
     - divided by language
  - Part manuals (?)
    - divided by language  (https://www.roadchoice.com/parts/bua102db)
  

Ticket 3:
  - Blogs
     - get metadata based on category - #41

Ticket 4:
  - Part fit - #55 (out of scope from this ticket)

**Open points:**
- Q: Is there any use case where a product belongs to two categories? If yes, which category do we show in the URL?
- A: There are no instances where a specific part number is listed under two different categories. We also don't link to specific product pages in our resources so redirects wouldn't be an requirement for this one.

**Comment by janedbarra** [comment]
There are no instances where a specific part number is listed under two different categories. We also don't link to specific product pages in our resources so redirects wouldn't be an requirement for this one.

**Comment by manuel-vara** [comment]
After solution design spike, we may need to keep the fixed part: https://roadchoice.com/**parts**/ to recognize url pages as dynamic PDP template

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking this ticket to done.
