### ISSUE TITLE
FR: Product Subcategory Template (dynamically created content)

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-roadchoice-com#78]
**Description**
The user uses the navigation (categories > electrical > batteries) to arrive to the Batteries Subcategory Template.

**Current situation:**
The structure of the URL to the product subcategory page is formed of:
- Fixed part: https://roadchoice.com/part-category/
- Subcategory: appended to each subcategory page
_Example: https://roadchoice.com/part-category/batteries_

**Future situation:**
The structure of the URL to the subcategory page is formed of:
- Fixed part: https://roadchoice.com/part-category/
- Category (ex. Electrical)
- Subcategory (ex. Batteries)
The data for the URL is retrieved automatically from the subcategory file ([rc_batteries](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BD98F331A-BB95-4DA4-8A9F-4BF6021BFF20%7D&file=RC_Batteries.xlsx&action=default&mobileredirect=true&cid=a7c0139f-0568-4726-8439-67791930e0ac)).
_Example: https://roadchoice.com/part-category/electrical/batteries/_
The editor creates and maintains the links to each of the existing subcategories in the Categories subnavigation menu document.

**Data mapping:**
**Data requirement is to find a naming convention for the [excel file](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BD98F331A-BB95-4DA4-8A9F-4BF6021BFF20%7D&file=RC_Batteries.xlsx&action=default&mobileredirect=true) to include the subcategory name (proposal: _rc_batteries_**)

**Acceptance criteria**
- The URL follows the described pattern
- The title displayed on the page is according to the subcategory the visitor is seeing
- The product list #36 , filters #37  and pagination #38  are OoS in this ticket, and will be done in their separate tickets 
- Create redirects from the previous URL to the new URL structure

**Comment by janedbarra** [comment]
Regarding the URL structure: This makes sense to me; however, would we have the ability to set up redirects? We have program summary documents that currently link to some of the product category pages. 

A thought around the open point, the Road Choice brand manager and I have been brainstorming ways to improve those category pages. However, we can keep as is for migration and then improve once we are on the Adobe platform.

**Comment by shirin27** [comment]
**Open point:**
- **Question**: Should we list the sub-categories on the product category page? (Ex. https://roadchoice.com/part-category/clutch would list all the clutch sub-categories), or should the access to the subcategory page stay only as part of the navigation?

**Comment by manuel-vara** [comment]
> **Open point:**
> 
> * **Question**: Should we list the sub-categories on the product category page? (Ex. https://roadchoice.com/part-category/clutch would list all the clutch sub-categories), or should the access to the subcategory page stay only as part of the navigation?

Based on the information we are able to get from the excel files currently, I think we should:
1. Include a fix part as `part-category` to recognize this specific dynamic template
2. Have only the subcategory that has the parts numbers as children. Example: We should use **https://roadchoice.com/part-category/batteries** instead of https://roadchoice.com/part-category/electrical/batteries
