### ISSUE TITLE
FR: PDP Template: Parts manuals block

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-roadchoice-com#81]
**Description**
Example of PDP with the section: https://roadchoice.com/parts/clak2175

**Data mapping**
Data source to be linked to the ticket -> [https://adobe.sharepoint.com/❌/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B7682F59E-14E0-4DF1-B0B0-FA625776E376%7D&file=catalogs-categories.xlsx&action=default&mobileredirect=true](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B7682F59E-14E0-4DF1-B0B0-FA625776E376%7D&file=catalogs-categories.xlsx&action=default&mobileredirect=true)

**Acceptance criteria**

- The patrs manuals section is displayed in an accordion
- The title and description are the same across different categories
- The table with resources is different, according to the category of the product
- When clicking on the link of the resource, the PDF is opened in a new tab

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/c679243e-499e-4902-aec8-8bf7b6e857b3)

**Comment by manuel-vara** [comment]
Open question: @Kannan-CM , is this based on subcategory as well? Please confirm.
Subcategory --> downloadable-pdf-1.pdf
Subcategory --> downloadable-pdf-2.pdf

**Comment by Varunvolvo** [comment]
Hi @manuel-vara 

We checked and found out that - Yes, it is based on subcategory as well 

Thanks, 
Varun U

**Comment by BeckyMedlin** [comment]
@manuel-vara Are we repurposing any of the Volvo or Mack accordions for Road Choice?

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results as per AC mentioned in ticket description :
Marking this ticket to done as all checks **except the minor defect #120** are passed. 

**Additional check :** The category (e.g. Batteries) in [source excel](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B7682F59E-14E0-4DF1-B0B0-FA625776E376%7D&file=catalogs-categories.xlsx&action=default&mobileredirect=true) is case insensitive & leading or trailing spaces in category / type columns data does not affect the functionality.

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/dd65438f-ae95-42bd-9626-cf3c9ac11359)
