### ISSUE TITLE
Bug: Medium: Pardot form: Bus pardot form layout is not as expected

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#88]
Steps:
1. Navigate to https://68-fr-pardot-forms--vg-roadchoice-com--hlxsites.hlx.page/drafts/mvara/forms/forms on chrome browser in desktop
2. Validate the bus form 

Expected:
1.  Bus Pardot form layout 
2. . 'ARE YOU A DEALER OR CUSTOMER? *'  has default value as 'Dealer'
3. 'COUNTRY *' mandatory input selection exists
4. 'BUSINESS NAME / COMPANY' input box is non mandatory

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/efa3c630-1088-4ab1-859b-d8f2dbc64fd2">

Actual:
1. Bus pardot form layout is not as expected
2. 'ARE YOU A DEALER OR CUSTOMER? *'  has no default value
3. 'COUNTRY *' mandatory input selection is not displayed
4. 'BUSINESS NAME / COMPANY' is renamed to 'COMPANY *' and made mandatory

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/e9f39af3-44cb-4797-a9b7-68b7bbcea524)

**Comment by BeckyMedlin** [comment]
@manuel-vara Is this caused because it is an iFrame vs a form handler?

**Comment by KJohnsn** [comment]
@girishdigrajkar can you include the browsers which this bug was found in?

**Comment by manuel-vara** [comment]
> @manuel-vara Is this caused because it is an iFrame vs a form handler? Please include details on the browsers in use when this is an issue.

Yes, it seems a CSS class conflict between parent page and iFrame form's styles.

**Comment by manuel-vara** [comment]
@jonatan-lledo-netcentric , can you pick up this one, please?
Please include this form into https://main--vg-roadchoice-com--hlxsites.hlx.page/bus

**Comment by BeckyMedlin** [comment]
@jonatan-lledo-netcentric @janedbarra Per discussion with Jane, ZIP Code is acceptable. The ZIP code field should display as: 
ZIP CODE/POSTAL CODE. She thinks this may be an Account Engagement issue and is meeting to discuss with Ryan Ropero on Wed., 10/11/23 to discuss the Account Engagement issue. Will update this ticket with info.

**Comment by janedbarra** [comment]
@jonatan-lledo-netcentric @BeckyMedlin I have updated styling and zip code/postal code on the form within Account Engagement. I believe this should resolve the spacing issue on the form? Here is the link directly from Account Engagement if that is helpful: https://go.roadchoice.com/l/999771/2023-08-04/mc6t

**Comment by jonatan-lledo-netcentric** [comment]
@janedbarra @BeckyMedlin, If you're okay with how the bus form looks, can we leave this issue as it is?

**Comment by janedbarra** [comment]
@jonatan-lledo-netcentric @BeckyMedlin yes, the bus form on this page (https://main--vg-roadchoice-com--hlxsites.hlx.page/bus) is fine. This ticket can be closed.

**Comment by girishdigrajkar** [comment]
Validated and based on above comments closing the ticket:

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/ab474492-dcef-4a4c-9494-c1c51aa5bdd0)
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/468468d5-2850-46cc-a2bd-e25d46bfdd56)
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/01d1beee-69f9-4768-97a1-1a33b4918e9a">
