### ISSUE TITLE
Bug: Medium: PDF opens in the same browser tab when clicked on any link on Catalog table block 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#95]
**Steps:**
**Scenario1:**
1. On desktop/chrome browser :   
        Navigate to https://45-catalogs-table-block--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs/  
2. Click on any link mentioned in  en/fr/es   Catalog / PRODUCT DATA SHEETS

**Scenario2**
1. On Mobile/ Tablet : chrome browser :   
        Navigate to https://45-catalogs-table-block--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs/  
2. Click on any link mentioned in  en/fr/es   Catalog / PRODUCT DATA SHEETS
3. Validate the page

**Expected:** 
1.  Desktop>> The PDF should open in separate tab however, the PDF opens in same tab
2.  Mobile/Tablet >> The PDF gets downloaded however, user in not navigated to PDF unlike earlier site implementation.
3.  Mobile only>>. The catalog/ product data sheets does not show **(notes)** in any of the link e.g. 
**Screenshot1:** 
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/2c0a059a-1403-426b-96be-a70114321e08">

**Screenshot3**
Mobile viewport does not display  notes column contents ..... however, it is displayed for desktop & tablet  
<img width="1783" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/6f1a171c-69df-4783-86df-cd0039141af8">

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/c050b92e-6823-4f39-b16b-6398490ee368)

**Comment by ZoeBeykirch** [comment]
@girishdigrajkar Same issue with the links only loading a blank page

**Comment by girishdigrajkar** [comment]
@ZoeBeykirch : Please try again it should be available now.

**Comment by BeckyMedlin** [comment]
@girishdigrajkar Is this truly a bug? Should've been created in the native Word app with the functionality that allows the page to open in another window.

**Comment by girishdigrajkar** [comment]
Hi @BeckyMedlin : Yes, it a bug as for same scenario with https://roadchoice.com/resources/catalogs/  URL it opens a separate window.

**Comment by girishdigrajkar** [comment]
Validated and now all links in https://main--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs opens in new window as expected hence, marking this defect to **done** status.

Also, For the notes column data it will be displayed on desktop and not on mobile viewport by implementation hence, no defect.
