### ISSUE TITLE
Bug: Medium: The Category name is not displayed in case the authored text in excel sheet is not in lower case.

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#96]
Steps:
1. On desktop/chrome browser :
   Navigate to https://45-catalogs-table-block--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs/
2. Validate the links mentioned in en/fr/es Catalog / PRODUCT DATA SHEETS

**Expected vs Actual:**
The Category name is not displayed in case the authored text in excel sheet is in capital letters.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/bc0ee7ec-e0c6-465f-9511-e568f8658a69">

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/4025466c-6cb9-48a4-9b94-e7531713dff6">

**Comment by ZoeBeykirch** [comment]
@girishdigrajkar The links aren't working for us to test, it only shows a blank page. Is there another link?

**Comment by girishdigrajkar** [comment]
Hi @ZoeBeykirch : Please try again it should be available now.

**Comment by BeckyMedlin** [comment]
@girishdigrajkar Should we also validate if an entry is in upper and lowercase (e.g., Catalog)?

**Comment by girishdigrajkar** [comment]
@BeckyMedlin : sure please;  This is active defect so, in case Category Name is in capital letter then it is not displayed on UI.  
Lowercase category names are successfully displayed.

**Comment by SantiagoHomps-NC** [comment]
This bug was already solved. Both type and language are not case sensitive and will accept any combination of casing among the considered options.
F.E.:
French: FE, fr, Fr, fR. -> all will work to select french language

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results: 
The record with capital case data for language i.e. EN & type as CATALOG is shown on UI successfully.

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/0bf81eff-9fc2-4bb8-8ef8-75522fa92ec1)

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/89697dcc-f094-4118-b0c7-55df3e9ce1b3)

**Comment by ZoeBeykirch** [comment]
closing ticket as status is deployed.
